
# -------------------------------
# GitLab CI/CD Pipeline
# File: .gitlab-ci.yml
# -------------------------------

# pipeline stages(executed in order)
stages:
  - build        
  - test         
  - deploy       

# -------------------------------
# Build Stage 
# -------------------------------
build:               
  stage: build           
  image: python:3.10     
  script:                
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Building application..."
    - python setup.py build
  artifacts:               
    paths:
      - build/           
    expire_in: 1 week    
  cache:                 
    paths:
      - .venv/           

# -------------------------------
# Test Stage 
# -------------------------------
test:              
  stage: test            
  image: python:3.10
  dependencies:         
    - build
  script:
    - echo "Running tests..."
    - pytest tests/      
  artifacts:
    when: always         
    reports:
      junit: report.xml  

# -------------------------------
# Deploy Stage 
# -------------------------------
deploy:             
  stage: deploy
  image: alpine:latest   
  environment:           
    name: production    
    url: https://example.com   
  script:
    - echo "Deploying application..."
    - ./deploy.sh        
  only:
    - main               

# -------------------------------
# Scheduled Job Example
# -------------------------------
nightly:
  stage: test
  script:
    - echo "Running nightly checks..."
  only:
    - schedules          
